version: '3'

services:
    postgresdb:
        container_name: postgres
        image: postgres:15-alpine
        networks:
            - app-net
        volumes:
            - sample_db:/var/lib/postgresql/data
        ports:
            - '5435:5432'
        environment:
            - POSTGRES_USERNAME
            - POSTGRES_PASSWORD
            - POSTGRES_DATABASE

volumes:
    sample_db:

networks:
    app-net:
        driver: bridge
